### ISSUE TITLE
Memory issue on V100s

### ISSUE THREAD

**Issue by raghukiran1224** [pytorch/workshops#13]
Observed OOM when running 737M T5 model on V100s with 32GB RAM each. The OOM was at the start of Epoch 1 after model was init-ed.

```
File "/home/hybridai/.local/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 514, in forward
    attn_weights = nn.functional.dropout(
  File "/home/hybridai/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1252, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 31.75 GiB total capacity; 30.42 GiB already allocated; 12.75 MiB free; 30.58 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Changing the batch size to 4 didnt fix the OOM, but it reduced the "tried to allocate" part. Further reducing to 2 for batch size as well as validation results in training to start. GPU utilization is high (98%), however the GPU memory is showing 24GB each (per `nvidia-smi`).

@lessw2020 suggests the following fixes:

> You are on V100 (so no BFloat16) and the code there does not have fp16 support added, so it's running in fp32 then, which is much more memory intensive.
> I can add in the shardedgradscaler for you tomorrow to add FP16, and also update it to use FSDP activation checkpointing rather than HF (which we are finding is more performant).
> For peak usage - I have a mem maximizer class that will show that for you.

**Comment by raghukiran1224** [comment]
@lessw2020 The other thing I notice from the above run is the peak memory utilization is not 32GB, but increasing the batch size does not help. Is there some assumption on the sharding that is causing this issue?

<img width="544" alt="image" src="https://user-images.githubusercontent.com/8322403/180218886-5684710d-a843-435d-8224-ab6d85bc50e4.png">

**Comment by lessw2020** [comment]
Forgot to update this issue but:
1 - ShardedGradScaler has been added to support FP16 (though we do not recommend FP16 for large language models...)
2 - FSDP activation checkpointing has been added 
3 - Mem maximizer which will add some additional memory stats during training has been added.

I'm going to close this out for now - feel free to ping directly for additional discussion.
